### ISSUE TITLE
@kl/-/components-v6-0.24.2.tgz: Request failed 404 Not Found

### ISSUE THREAD

**Issue by promo360** [KasperskyLab/uif#10]
package.json (ui-builder) contains dependencies @kl/components-v6, @kl/dev-tools, @kl/runtime that can't be installed.

```
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.npmjs.org/@kl/components-v6/-/@kl/-/components-v6-0.24.2.tgz: Request failed \"404 Not Found\"".
```

**Comment by vostrik** [comment]
@promo360 I just fixed this behaviour in #23. Please, check updated sources and README file at `@kaspersky/ui-builder`.
