### ISSUE TITLE
yarn.lock contains broken links to packages (405 Method Not Allowed)

### ISSUE THREAD

**Issue by promo360** [KasperskyLab/uif#8]
I'm trying to install dependencies in ui-builder but I'm getting the error

```sh
https://registry.npmjs.org/image-size/image-size-0.5.5.tgz: Request failed "405 Method Not Allowed"
```

Link to package in yarn.lock: https://registry.npmjs.org/interpret/interpret-1.2.0.tgz#d5061a6224be58e8083985f5014d844359576296

Correct link: https://registry.npmjs.org/interpret/-/interpret-1.2.0.tgz#d5061a6224be58e8083985f5014d844359576296

This is not the only package with a broken link

**Comment by vostrik** [comment]
We need to fix next packages after open source publication:

- [ ] dev-tools
- [ ] runtime
- [ ] ui builder
- [ ] components
